language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  # api_key:
  #   secure: CVhzLX0519AXGmkzEX8PQNvTDMifTw3hqrcsQjNl4M6BscealedkpMetWQFcGYoVnyujAdFD39V1c1LN8/3PiDgjtokrjUcChHcE7LJDRU845r/Uh7KwyWQFHW9Lk1JOTaFApnIYsz5l6+KlHyJeZb2JPxxG1ME94Grtab5USdBTgUKShuVUrZVpXoO0bbNFJfPRp9jmtB4TbVJ4uoO3tblrqWAEGe8u5YtzcUA7POnhlraRzyPRScgCzsoxt2tMrXJKobbo9jYR6fbrWCQEwbax0zHxHi+aP9XFNSmFXsiiqhCcvQY11jf13bGFfrslWcSH+O+OeQNCJisupGMQJ0FQJ7qp1l2WMizjHcxXEvrCpjTd+BNgHvFuXE5WqsOpLYWexPDtFhCgHDj6ukeUUO85Uprnl0f0NXrvW3zShTsznWzal7G30ogba0GS5KHRx0QbfpUrJUUgflMaq3+ET7rKS2WY+pAR+UJK40vZdPWXRmOYFaBQSFDeys8XiHi0ZBkKR0FxdrI6RIO+UVwa3uJMrBC4YuuMmdrXDfPLMwYvkdIpyB6hK2cHncY50CyHzl6rbrqWX7Dkqvq2aH4m4FbVtSeu7F7xTfd878xtK2KBmbElVxUtsaUqP6IBOUozIrO3NVArkeIqfwVUhnd6mhAzxh/WMlWY60kPSV8wpdI=
  app: desolate-ravine-91436
  on:
    repo: mmarovich/politics3.0
